# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  github_provider_key: <%= ENV["GH_PROVIDER_KEY"] %>
  github_provider_secret: <%= ENV["GH_PROVIDER_SECRET"] %>
  secret_key_base: 8c030a65596063f7bb769e70853122810c6d3df42666894b1cbf6ffbe13e76f15816ef49746ecaf4afbf5b8d97486a89fb9a48336483e8df1a731ef04cd8dc0b

test:
  secret_key_base: df05ee0ab25b8b0e54443a46b880d7f4c4982dfb529d0cb8859eb137db5b98d93add6935413d743c3ec01aa38934cbbed89acc681284320d455b1d0db0c5f606
  github_provider_key: <%= ENV["GH_PROVIDER_KEY"] %>
  github_provider_secret: <%= ENV["GH_PROVIDER_SECRET"] %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  github_provider_key: <%= ENV["GH_PROVIDER_KEY"] %>
  github_provider_secret: <%= ENV["GH_PROVIDER_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
